### ISSUE TITLE
Just a question, really

### ISSUE THREAD

**Issue by t0m-f00l3ry** [codedarkness/spectrwm#1]
I love your configs man, in particular the way you steam your rice. 
When it comes to configuring and piping conky, I can't seem to get the BAT or VOL modules to work properly. I uncommented the BAT section, and as far as I can tell it is pulling info for BAT0. Yet BAT isn't even showing up on the bar. Do I need to add a part to the "bar_format" line in the main conf?

**Comment by codedarkness** [comment]
Hey, How's it going?
Try to change the battery module to:
BAT **${battery_short BAT0}** (or check the battery number in your system)
For the volume module, do you have installed ALSA...
